### ISSUE TITLE
版本兼容

### ISSUE THREAD

**Issue by banjuer** [imcnchl/siyuan-plugin-more-cover#2]
非常nice的插件，不过
思源：v3.0.4
提示不兼容
![image](https://github.com/imcnchl/siyuan-plugin-more-cover/assets/18739609/6f66b81b-8073-4fb5-93a6-0f8ecd5d9962)

**Comment by imcnchl** [comment]
嗯，这个我最近会调整，不过最近两周应该没有时间

**Comment by imcnchl** [comment]
v1.0.7版本已经处理了不能使用的问题，晚点集市中可以更新
