### ISSUE TITLE
无法唤出随机题头图的图片选择界面

### ISSUE THREAD

**Issue by QMike0** [imcnchl/siyuan-plugin-more-cover#4]
思源版本：v3.0.13，插件版本：v1.0.5
已完成Unsplash密钥的配置：
![image](https://github.com/imcnchl/siyuan-plugin-more-cover/assets/43239563/a48fa1a0-be0b-41bc-833c-cc05d28e8925)
对应Unsplash中的配置为：
![image](https://github.com/imcnchl/siyuan-plugin-more-cover/assets/43239563/3d346262-8bed-4e39-8887-2b875fad31c6)
![image](https://github.com/imcnchl/siyuan-plugin-more-cover/assets/43239563/af569bdf-2b26-41b5-8e3b-79344cc24575)
然而无法在题头图中打开Unsplash的图片选择界面，尝试了所有选项都不行：
![recording](https://github.com/imcnchl/siyuan-plugin-more-cover/assets/43239563/a11e87fa-bfe7-49d2-ab45-9f624366cb5b)
之前已经用过好长时间这个插件，一直都是正常的。不知道是因为思源用了新版本Electron、插件更新还是其他原因，现在很奇怪地就用不了了，来求助一下

**Comment by imcnchl** [comment]
v1.0.7版本已经处理了不能使用的问题，晚点集市中可以更新
